//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoNgay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoNgay()
        {
            this.DonBien_A2 = new HashSet<DonBien_A2>();
            this.HDT_B2 = new HashSet<HDT_B2>();
            this.HTD_B3 = new HashSet<HTD_B3>();
            this.QuanBuu_47_B4 = new HashSet<QuanBuu_47_B4>();
            this.QuanBuu_CongVan_B4 = new HashSet<QuanBuu_CongVan_B4>();
            this.QuanBuu_HoaToc_B4 = new HashSet<QuanBuu_HoaToc_B4>();
            this.QuanBuu_PhuongTien_B4 = new HashSet<QuanBuu_PhuongTien_B4>();
            this.QuanBuu_ThuBao_B4 = new HashSet<QuanBuu_ThuBao_B4>();
            this.QuanBuu_VanKien_B4 = new HashSet<QuanBuu_VanKien_B4>();
            this.SCN_A4 = new HashSet<SCN_A4>();
            this.SongNgan_BTTM_A3 = new HashSet<SongNgan_BTTM_A3>();
            this.SongNgan_HiepDong_A3 = new HashSet<SongNgan_HiepDong_A3>();
            this.SongNgan_NoiBo_A3 = new HashSet<SongNgan_NoiBo_A3>();
            this.TBBD_A1 = new HashSet<TBBD_A1>();
            this.ViBa_A6 = new HashSet<ViBa_A6>();
        }
    
        public int BaoCaoID { get; set; }
        public string NguoiBaoCao { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public Nullable<int> DonViID { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsGui { get; set; }
        public string TrucBanTruong { get; set; }
        public string TrucBanPho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonBien_A2> DonBien_A2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDT_B2> HDT_B2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTD_B3> HTD_B3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_47_B4> QuanBuu_47_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_CongVan_B4> QuanBuu_CongVan_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_HoaToc_B4> QuanBuu_HoaToc_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_PhuongTien_B4> QuanBuu_PhuongTien_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_ThuBao_B4> QuanBuu_ThuBao_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanBuu_VanKien_B4> QuanBuu_VanKien_B4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCN_A4> SCN_A4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongNgan_BTTM_A3> SongNgan_BTTM_A3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongNgan_HiepDong_A3> SongNgan_HiepDong_A3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongNgan_NoiBo_A3> SongNgan_NoiBo_A3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBBD_A1> TBBD_A1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViBa_A6> ViBa_A6 { get; set; }
    }
}
