//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDT_B2
    {
        public int B2_ID { get; set; }
        public Nullable<int> SoDoiTuong { get; set; }
        public Nullable<int> LanChuyenTiep { get; set; }
        public Nullable<int> SoLanDut { get; set; }
        public Nullable<int> DayTieuHao { get; set; }
        public Nullable<int> GioLienLac { get; set; }
        public Nullable<int> PhutLienLac { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaoCaoID { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
    }
}
