//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTD_B3
    {
        public int B3_ID { get; set; }
        public Nullable<int> MayDung { get; set; }
        public Nullable<int> MaySua { get; set; }
        public Nullable<int> MayDong { get; set; }
        public Nullable<int> DatMayMoi { get; set; }
        public Nullable<int> TongSoTrKe { get; set; }
        public Nullable<int> TongSoTrKe_Dut { get; set; }
        public Nullable<int> TongSoTrKeNB { get; set; }
        public Nullable<int> TongSoTrKeNB_Dut { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaoCaoID { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
    }
}
