//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TTQK7Entities : DbContext
    {
        public TTQK7Entities()
            : base("name=TTQK7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoNgay> BaoCaoNgay { get; set; }
        public virtual DbSet<DonBien_A2> DonBien_A2 { get; set; }
        public virtual DbSet<HDT_B2> HDT_B2 { get; set; }
        public virtual DbSet<HTD_B3> HTD_B3 { get; set; }
        public virtual DbSet<QuanBuu_47_B4> QuanBuu_47_B4 { get; set; }
        public virtual DbSet<QuanBuu_CongVan_B4> QuanBuu_CongVan_B4 { get; set; }
        public virtual DbSet<QuanBuu_HoaToc_B4> QuanBuu_HoaToc_B4 { get; set; }
        public virtual DbSet<QuanBuu_PhuongTien_B4> QuanBuu_PhuongTien_B4 { get; set; }
        public virtual DbSet<QuanBuu_ThuBao_B4> QuanBuu_ThuBao_B4 { get; set; }
        public virtual DbSet<QuanBuu_VanKien_B4> QuanBuu_VanKien_B4 { get; set; }
        public virtual DbSet<SCN_A4> SCN_A4 { get; set; }
        public virtual DbSet<SongNgan_BTTM_A3> SongNgan_BTTM_A3 { get; set; }
        public virtual DbSet<SongNgan_HiepDong_A3> SongNgan_HiepDong_A3 { get; set; }
        public virtual DbSet<SongNgan_NoiBo_A3> SongNgan_NoiBo_A3 { get; set; }
        public virtual DbSet<TBBD_A1> TBBD_A1 { get; set; }
        public virtual DbSet<tblChucVu> tblChucVu { get; set; }
        public virtual DbSet<tblDonVi> tblDonVi { get; set; }
        public virtual DbSet<tblMail> tblMail { get; set; }
        public virtual DbSet<tblMailFile> tblMailFile { get; set; }
        public virtual DbSet<tblMailUser> tblMailUser { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<TrucBan> TrucBan { get; set; }
        public virtual DbSet<ViBa_A6> ViBa_A6 { get; set; }
        public virtual DbSet<tblUploadFile> tblUploadFile { get; set; }
    
        public virtual ObjectResult<BaoCaoTongHop_Result> BaoCaoTongHop(Nullable<int> ngay, Nullable<int> thang, Nullable<int> nam)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaoCaoTongHop_Result>("BaoCaoTongHop", ngayParameter, thangParameter, namParameter);
        }
    
        public virtual ObjectResult<BaoCaoTongHopHuyen_Result> BaoCaoTongHopHuyen(Nullable<int> dvid, Nullable<int> ngay, Nullable<int> thang, Nullable<int> nam)
        {
            var dvidParameter = dvid.HasValue ?
                new ObjectParameter("dvid", dvid) :
                new ObjectParameter("dvid", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaoCaoTongHopHuyen_Result>("BaoCaoTongHopHuyen", dvidParameter, ngayParameter, thangParameter, namParameter);
        }
    
        public virtual ObjectResult<string> Get_DSNguoiNhan(Nullable<int> idMail)
        {
            var idMailParameter = idMail.HasValue ?
                new ObjectParameter("idMail", idMail) :
                new ObjectParameter("idMail", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_DSNguoiNhan", idMailParameter);
        }
    
        public virtual ObjectResult<Get_ListMailInbox_Result> Get_ListMailInbox(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ListMailInbox_Result>("Get_ListMailInbox", idUserParameter);
        }
    
        public virtual ObjectResult<Get_ListMailSent_Result> Get_ListMailSent(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ListMailSent_Result>("Get_ListMailSent", idUserParameter);
        }
    
        public virtual ObjectResult<p_BaoCaoTongHop_View_Result> p_BaoCaoTongHop_View(Nullable<int> ngay, Nullable<int> thang, Nullable<int> nam)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_BaoCaoTongHop_View_Result>("p_BaoCaoTongHop_View", ngayParameter, thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_Thanh_BaoCaoThang_Result> sp_Thanh_BaoCaoThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Thanh_BaoCaoThang_Result>("sp_Thanh_BaoCaoThang", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_Thanh_BaoCaoThang_DonVi_Result> sp_Thanh_BaoCaoThang_DonVi(Nullable<int> thang, Nullable<int> nam, Nullable<int> idDonVi)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var idDonViParameter = idDonVi.HasValue ?
                new ObjectParameter("idDonVi", idDonVi) :
                new ObjectParameter("idDonVi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Thanh_BaoCaoThang_DonVi_Result>("sp_Thanh_BaoCaoThang_DonVi", thangParameter, namParameter, idDonViParameter);
        }
    }
}
