//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanBuu_PhuongTien_B4
    {
        public int B4_PhuongTien_ID { get; set; }
        public Nullable<int> XeDap { get; set; }
        public Nullable<int> MoTo { get; set; }
        public Nullable<int> OTo { get; set; }
        public Nullable<int> SoChuyen { get; set; }
        public Nullable<double> TrongLuong { get; set; }
        public Nullable<int> CuLy { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaoCaoID { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
    }
}
