//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBD_A1
    {
        public int A1_ID { get; set; }
        public Nullable<int> CanhBTTM { get; set; }
        public Nullable<int> CanhBTTM_Dut { get; set; }
        public Nullable<int> CanhQK { get; set; }
        public Nullable<int> CanhQK_Dut { get; set; }
        public Nullable<int> Lanphatchuan { get; set; }
        public Nullable<int> ThuTinHieuBo { get; set; }
        public Nullable<int> ThuTinHieuQK { get; set; }
        public Nullable<int> QKPhatTinHieu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaoCaoID { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
    }
}
