//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMailFile
    {
        public int idFile { get; set; }
        public Nullable<int> idMail { get; set; }
        public string TenFile { get; set; }
    
        public virtual tblMail tblMail { get; set; }
    }
}
