//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMailUser
    {
        public int idMailUser { get; set; }
        public Nullable<int> idMail { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string TraLoi { get; set; }
    
        public virtual tblMail tblMail { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
