//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadFile
    {
        public int ID { get; set; }
        public string NameFile { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> DonViID { get; set; }
    
        public virtual tblDonVi tblDonVi { get; set; }
    }
}
