//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrucBan
    {
        public int TrucBanID { get; set; }
        public string TrucBanTruong { get; set; }
        public string TrucBanPho { get; set; }
        public Nullable<System.DateTime> NgayTruc { get; set; }
        public Nullable<int> DonViID { get; set; }
    }
}
