//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTQK7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViBa_A6
    {
        public int A6_ID { get; set; }
        public Nullable<int> SoDoiTuong { get; set; }
        public Nullable<int> GioLienLac { get; set; }
        public Nullable<int> GioPhatLienLac { get; set; }
        public Nullable<int> GioPhat { get; set; }
        public Nullable<int> GioPhat_Dut { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaoCaoID { get; set; }
    
        public virtual BaoCaoNgay BaoCaoNgay { get; set; }
    }
}
